service: website-checker-bot-yc
frameworkVersion: "3"

provider:
  name: yandex-cloud
  runtime: nodejs16
  httpApi:
    payload: '1.0'


plugins:
  - "@yandex-cloud/serverless-plugin"

package:
  patterns:
    - '!**'
    - package.json
    - package-lock.json
    - dist/*.js

functions:
  web:
    handler: dist/index.web
    memorySize: 128
    timeout: '5'
    account: website-checker-bot-yc-sa
    environment:
      ENDPOINT: ${lockbox:e6qtpi769u9fdrcr8c2t/ENDPOINT}
      DATABASE: ${lockbox:e6qtpi769u9fdrcr8c2t/DATABASE}
      BOT_KEY: ${lockbox:e6qtpi769u9fdrcr8c2t/BOT_KEY}
    events:
      - http:
          method: post
          path: /

  timer:
    handler: dist/index.timer
    memorySize: 128
    timeout: '30'
    account: website-checker-bot-yc-sa
    environment:
      ENDPOINT: ${lockbox:e6qtpi769u9fdrcr8c2t/ENDPOINT}
      DATABASE: ${lockbox:e6qtpi769u9fdrcr8c2t/DATABASE}
      BOT_KEY: ${lockbox:e6qtpi769u9fdrcr8c2t/BOT_KEY}
    events:
      - cron:
          expression: "0 * * * ? *"
          account: website-checker-bot-yc-sa



resources:
  website-checker-bot-yc-sa:
    type: yc::ServiceAccount
    roles:
      - serverless.functions.invoker
      - ydb.editor

