service: templates\nodejs
frameworkVersion: "3"

provider:
  name: yandex-cloud
  runtime: nodejs16
  httpApi:
    payload: '1.0'


plugins:
  - "@yandex-cloud/serverless-plugin"

package:
  patterns:
    - '!**'
    - package.json
    - package-lock.json
    - dist/*.js

functions:
  simple:
    handler: dist/index.hello
    memorySize: 128
    timeout: '5'
    account: function-sa
    events:
      - http:
          method: post
          path: /post/just/to/this/path

  timer:
    handler: dist/index.hello
    memorySize: 128
    timeout: '5'
    events:
      - cron:
          expression: "* * * * ? *"
          account: trigger-sa
          retry:
            attempts: 1
            interval: 10

resources:
  trigger-sa:
    type: yc::ServiceAccount
    roles:
      - serverless.functions.invoker
  function-sa:
    type: yc::ServiceAccount
    roles:
      - editor
